version: "3.7"
services:
  nginx:
    image: nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
  php:
    image: php:7-fpm
    volumes:
      - ./public:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

